main:
  - name: Music
    pageRef: music
    weight: 10
  - name: Authors
    pageRef: Authors
    weight: 20
  - identifier: github
    pre: github
    url: 'https://github.com/jsasd/js-drumline'
    weight: 100
  - identifier: facebook
    pre: facebook
    url: 'https://www.facebook.com/JerseyShoreHighSchoolBand'
    weight: 200

footer:
  - name: Music
    pageRef: music
    weight: 10
  - name: Authors
    pageRef: authors
    weight: 20