colorScheme: fire
defaultAppearance: dark
autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: true

mainSections:
  - docs

disableImageOptimization: false
defaultBackgroundImage: /img/background.png
defaultFeaturedImage: /img/background.png
highlightCurrentMenuArea: true
smartTOC: true
smartTOCHideUnfocusedChildren: true

header:
  layout: fixed

footer:
  showMenu: true
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true

homepage:
  layout: background
  showRecent: true
  showRecentItems: 6
  showMoreLink: true
  showMoreLinkDest: docs
  cardView: false
  cardViewScreenWidth: false
  layoutBackgroundBlur: true

article:
  showDate: false
  showViews: true
  showLikes: true
  showDateUpdated: false
  showAuthor: true
  showHero: true
  heroStyle: background
  layoutBackgroundBlur: true
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: true
  editURL: 'https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content'
  editAppendPath: true
  seriesOpened: false
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: true
  showTableOfContents: true
  showRelatedContent: true
  relatedContentLimit: 6
  showTaxonomies: true
  showAuthorsBadges: true
  showWordCount: false
  showSummary: true
  sharingLinks:
    - linkedin
    - twitter
    - reddit
    - whatsapp
    - telegram
    - pinterest
    - facebook
    - email

list:
  showHero: true
  heroStyle: background
  layoutBackgroundBlur: true
  layoutBackgroundHeaderSpace: false
  showBreadcrumbs: false
  showSummary: false
  showViews: true
  showLikes: true
  showTableOfContents: true
  showCards: true
  groupByYear: false
  cardView: true
  cardViewScreenWidth: false
  constrainItemsWidth: false

sitemap:
  excludedKinds:
    - taxonomy
    - term

taxonomy:
  showTermCount: true
  showHero: true
  heroStyle: background
  showBreadcrumbs: false
  showViews: true
  showLikes: true
  showTableOfContents: true
  cardView: false

term:
  showHero: true
  heroStyle: background
  showBreadcrumbs: false
  showViews: true
  showLikes: true
  showTableOfContents: true
  groupByYear: false
  cardView: true
  cardViewScreenWidth: false

fathomAnalytics: {}

verification: {}
